### ISSUE TITLE
/shift manage issue

### ISSUE THREAD

**Issue by motionzlol** [bugsbirb/TridERMly#2]
Just trying it out for just research, getting this error whilst running the command /shift manage

2024-09-17 15:09:38 ERROR    discord.ui.view Ignoring exception in view <ShiftManage timeout=180.0 children=3> for item <Button style=<ButtonStyle.success: 3> url=None disabled=False label='Start' emoji=None row=None sku_id=None>
Traceback (most recent call last):
  File "C:\Users\G**\\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ui\view.py", line 430, in _scheduled_task
    await item.callback(interaction)
  File "C:\Users\G**\\Desktop\TridERMly-master\Modules\shifts.py", line 323, in start
    ShiftResult = await shifts.find_one(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\G**\\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\G**\\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\collection.py", line 1495, in find_one
    for result in cursor.limit(-1):
                  ^^^^^^^^^^^^^^^^
  File "C:\Users\G**\\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\cursor.py", line 1243, in next
    if len(self.__data) or self._refresh():
                           ^^^^^^^^^^^^^^^
  File "C:\Users\G**\\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\cursor.py", line 1160, in _refresh
    self.__send_message(q)
  File "C:\Users\G**\\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\cursor.py", line 1039, in __send_message
    response = client._run_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\G**\\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\G**\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\mongo_client.py", line 1431, in _run_operation
    return self._retryable_read(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\G**\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\mongo_client.py", line 1540, in _retryable_read
    return self._retry_internal(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\G**\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\G**\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\mongo_client.py", line 1507, in _retry_internal
    ).run()
      ^^^^^
  File "C:\Users\G**\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\mongo_client.py", line 2353, in run
    return self._read() if self._is_read else self._write()
           ^^^^^^^^^^^^
  File "C:\Users\G**\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\mongo_client.py", line 2491, in _read
    return self._func(self._session, self._server, conn, read_pref)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\G**\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\mongo_client.py", line 1422, in _cmd
    return server.run_operation(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\G**\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\helpers.py", line 342, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\G**\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\server.py", line 190, in run_operation
    _check_command_response(first, conn.max_wire_version)
  File "C:\Users\Gaming pc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymongo\helpers.py", line 248, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: unknown operator: guild, full error: {'ok': 0.0, 'errmsg': 'unknown operator: guild', 'code': 2, 'codeName': 'BadValue', '$clusterTime': {'clusterTime': Timestamp(1726582176, 1), 'signature': {'hash': b'\xb2"\xf2a\x91\xa5(\xa7~\x92:\xcf\xba\xd1S;\xf5R}\xd9', 'keyId': 7374468420714102786}}, 'operationTime': Timestamp(1726582176, 1)}

**Comment by motionzlol** [comment]
The whole shift system is broken by the way.

**Comment by bugsbirb** [comment]
Fixed in new update.
